palette = "catppuccin_mocha"

format = """$username\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""
add_newline = false

[username]
show_always = true
format = "[$user ](green1)"

[directory]
format = "[$path](blue1) "
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[❯](green1)"
error_symbol = "[❯](red1)"
vimcmd_symbol = "[❮](green1)"

[git_branch]
format = "[$branch]($style)"
style = "green2"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "blue1"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "green2"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow1"

[python]
format = "[$virtualenv]($style) "
style = "yellow1"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#add7ff"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
mantle = "#181825"
crust = "#11111b"
base = "#1b1e28"
red1 = "#d0679d"
red2 = "#fcc5e9"
yellow1 = "#fffac2"
green1 = "#5de4c7"
green2 = "#5fb3a1"
blue1 = "#add7ff"
blue2 = "#89ddff"
text1 = "#ffffff"
text2 = "#e4f0fb"
grey1 = "#a6accd"
grey2 = "#506477"
grey3 = "#303340"
grey4 = "#1b1e28"
grey5 = "#171922"
subtext2 = "#5de4c7"
